site_name: netboot.xyz
site_description: netboot.xyz uses iPXE to network boot Operating System installers and utilities from an easy to use menu.
site_author: netboot.xyz
site_url: https://netboot.xyz
repo_url: https://github.com/antonym/netboot.xyz
copyright: Â© 2018 <a href="https://twitter.com/@ntonym">Antony Messerli</a>
docs_dir: docs
google_analytics: ['UA-68807-15', 'netboot.xyz']
pages:
- Home: 'index.md'
- Boot from...:
#    - 'Extlinux/Grub': 'boot-loaders.md'
    - 'iPXE': 'boot-ipxe.md'
    - 'ISO': 'boot-iso.md'
    - 'TFTP': 'boot-tftp.md'
    - 'USB': 'boot-usb.md'
#    - 'Virtual Box': 'boot-vbox.md'
    - 'VMware': 'boot-vmware.md'
- Provider Usage:
    - 'Digital Ocean': 'usage-digitalocean.md'
    - 'Google Compute Engine': 'usage-gce.md'
    - 'OpenStack': 'usage-openstack.md'
    - 'Packet': 'usage-packet.md'
    - 'Rackspace': 'usage-rackspace.md'
    - 'Vultr': 'usage-vultr.md'
- FAQ: 'faq.md'
- Contributing: 'contributing.md'
theme: yeti
