site_name: netboot.xyz
site_description: netboot.xyz uses iPXE to boot multiple Operating System installers or utilities over the network from a single menu.
site_author: netboot.xyz
site_url: http://netboot.xyz
repo_url: https://github.com/antonym/netboot.xyz
copyright: Â© 2016 <a href="https://twitter.com/ajmesserli">Antony Messerli</a>
docs_dir: docs
google_analytics: ['UA-68807-15', 'netboot.xyz']
pages:
- Home: 'index.md'
- Boot from...:
#    - 'Extlinux/Grub': 'boot-loaders.md'
    - 'iPXE': 'boot-ipxe.md'
    - 'ISO': 'boot-iso.md'
    - 'TFTP': 'boot-tftp.md'
    - 'USB': 'boot-usb.md'
#    - 'Virtual Box': 'boot-vbox.md'
#    - 'VMware': 'boot-vmware.md'
- Provider Usage:
    - 'Digital Ocean': 'usage-digitalocean.md'
    - 'Rackspace': 'usage-rackspace.md'
theme: yeti
