---
  - name: Combine overrides with release defaults
    set_fact:
      _releases: "{{ releases|combine(release_overrides, recursive=True) }}"
    when: release_overrides is defined

  - name: Set releases with user overrides
    set_fact:
      releases: "{{ _releases }}"
    when: release_overrides is defined

    # PC BIOS utilities
  - name: Combine overrides with utilitiespcbios defaults
    set_fact:
      _utilitiespcbios: "{{ utilitiespcbios|combine(utilitiespcbios_overrides, recursive=True) }}"
    when: utilitiespcbios_overrides is defined

  - name: Set utilitypcbios with user overrides
    set_fact:
      utilitiespcbios: "{{ _utilitiespcbios }}"
    when: utilitiespcbios_overrides is defined

    # EFI utilities
  - name: Combine overrides with utilitiesefi defaults
    set_fact:
      _utilitiesefi: "{{ utilitiesefi|combine(utilitiesefi_overrides, recursive=True) }}"
    when: utilitiesefi_overrides is defined

  - name: Set utilityefi with user overrides
    set_fact:
      utilitiesefi: "{{ _utilitiesefi }}"
    when: utilitiesefi_overrides is defined

  - name: Generate directories
    file:
      path: "{{ netbootxyz_root }}"
      state: directory

  - name: Set menu version
    set_fact:
      upstream_version: "{{ boot_version }}"
    when:
      - generate_version_file | bool

  - name: Generate version.ipxe for upstream
    template:
      src: "version.ipxe.j2"
      dest: "{{ netbootxyz_root }}/version.ipxe"
    when:
      - generate_version_file | bool

  - name: Generate netboot.xyz source files templates
    template:
      src: "{{ item.src }}"
      dest: "{{ netbootxyz_root }}/{{ item.path | regex_replace('.j2','') }}"
    with_filetree: "templates/menu/"
    when: item.state == "file"
    tags:
    - skip_ansible_lint

  - name: Retrieve pciids.ipxe
    get_url:
      url: "{{ pciids_url }}"
      dest: "{{ netbootxyz_root }}/pciids.ipxe"
