---

  - name: Copy netboot.xyz local EFI iPXE configs
    copy:
      src: "ipxe/local/{{ item }}"
      dest: "{{ ipxe_source_dir }}/src/config/local/{{ item }}"
    with_items:
      - colour.h
      - console.h
      - crypto.h

  - name: Copy netboot.xyz general.h.efi iPXE config
    copy:
      src: "ipxe/local/general.h.efi"
      dest: "{{ ipxe_source_dir }}/src/config/local/general.h"

  - name: Set trust file to ipxe ca
    set_fact:
      trust_files: "{{ cert_dir }}/{{ ipxe_ca_filename }}"
    when: not generate_signatures

  - name: Combine trust files if set
    set_fact:
      trust_files: "{{ cert_dir }}/{{ ipxe_ca_filename }},{{ cert_dir }}/{{ cert_file_filename }}"
    when: generate_signatures | bool

  - name: Compile iPXE bootloader for EFI
    shell: |
      make clean
      make EMBED={{ bootloader_filename }} \
           TRUST={{ trust_files }} \
           bin-x86_64-efi/ipxe.efi \
           bin-x86_64-efi/snp.efi \
           bin-x86_64-efi/snponly.efi
    args:
      chdir: "{{ ipxe_source_dir }}/src"
    tags:
    - skip_ansible_lint

  - name: Copy iPXE EFI builds to http directory
    copy:
      src: "{{ ipxe_source_dir }}/src/{{ item.src }}"
      dest: "{{ netbootxyz_root }}/ipxe/{{ item.dest }}"
      remote_src: True
    with_items:
      - { src: "bin-x86_64-efi/ipxe.efi", dest: "{{ bootloader_filename }}.efi" }
      - { src: "bin-x86_64-efi/snp.efi", dest: "{{ bootloader_filename }}-snp.efi" }
      - { src: "bin-x86_64-efi/snponly.efi", dest: "{{ bootloader_filename }}-snponly.efi" }
    when: bootloader_filename != "netboot.xyz-packet"

  - name: Copy iPXE EFI builds to http directory for packet
    copy:
      src: "{{ ipxe_source_dir }}/src/{{ item.src }}"
      dest: "{{ netbootxyz_root }}/ipxe/{{ item.dest }}"
      remote_src: True
    with_items:
      - { src: "bin-x86_64-efi/ipxe.efi", dest: "{{ bootloader_filename }}.efi" }
    when: bootloader_filename == "netboot.xyz-packet"
