---

- name: Generate directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ custom_templates_dir }}"
    - "{{ netbootxyz_root }}/custom"

- name: Generate custom user menu templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ netbootxyz_root }}/custom/{{ item.path | regex_replace('.j2', '') }}"
  with_community.general.filetree: "{{ custom_templates_dir }}"
  when: item.state == "file"
