---

- name: Copy netboot.xyz local EFI iPXE configs
  ansible.builtin.copy:
    src: "ipxe/local/{{ item }}"
    dest: "{{ ipxe_source_dir }}/src/config/local/{{ item }}"
  with_items:
    - colour.h
    - console.h
    - crypto.h

- name: Copy netboot.xyz general.h.efi iPXE config
  ansible.builtin.copy:
    src: "ipxe/local/general.h.efi"
    dest: "{{ ipxe_source_dir }}/src/config/local/general.h"

- name: Set trust file to ipxe ca
  ansible.builtin.set_fact:
    trust_files: "{{ cert_dir }}/{{ ipxe_ca_filename }}"
  when: not generate_signatures

- name: Combine trust files if set
  ansible.builtin.set_fact:
    trust_files: "{{ cert_dir }}/{{ ipxe_ca_filename }},{{ cert_dir }}/{{ cert_file_filename }}"
  when: generate_signatures | bool

- name: Compile iPXE bootloader for EFI
  ansible.builtin.shell: |
    make clean
    make -j{{ make_num_jobs }} \
         EMBED={{ bootloader_filename }} \
         TRUST={{ trust_files }} \
         bin-x86_64-efi/ipxe.efi \
         bin-x86_64-efi/snp.efi \
         bin-x86_64-efi/snponly.efi
  args:
    chdir: "{{ ipxe_source_dir }}/src"
  when: ipxe_debug_enabled | bool == false

- name: Compile iPXE bootloader for EFI with debug flags
  ansible.builtin.shell: |
    make clean
    make -j{{ make_num_jobs }} \
         EMBED={{ bootloader_filename }} \
         DEBUG={{ ipxe_debug_options }} \
         TRUST={{ trust_files }} \
         bin-x86_64-efi/ipxe.efi \
         bin-x86_64-efi/snp.efi \
         bin-x86_64-efi/snponly.efi
  args:
    chdir: "{{ ipxe_source_dir }}/src"
  when: ipxe_debug_enabled | bool

- name: Copy iPXE EFI builds to http directory
  ansible.builtin.copy:
    src: "{{ ipxe_source_dir }}/src/{{ item.src }}"
    dest: "{{ netbootxyz_root }}/ipxe/{{ item.dest }}"
    remote_src: true
  with_items:
    - {src: "bin-x86_64-efi/ipxe.efi", dest: "{{ bootloader_filename }}.efi"}
    - {src: "bin-x86_64-efi/snp.efi", dest: "{{ bootloader_filename }}-snp.efi"}
    - {src: "bin-x86_64-efi/snponly.efi", dest: "{{ bootloader_filename }}-snponly.efi"}
