---

### site configuration ###
site_name: netboot.xyz
boot_domain: boot.netboot.xyz
boot_version: 1.04
boot_timeout: 300000

time_server: "0.pool.ntp.org"
sigs_enabled: false
img_sigs_enabled: false
sigs_location: "http://${boot_domain}/sigs/"
memdisk_location: "http://${boot_domain}/memdisk"

ipxe_repo: https://github.com/ipxe/ipxe.git
ipxe_branch: master
ipxe_source_dir: /usr/src/ipxe

live_endpoint: "https://github.com/netbootxyz"
netbootxyz_root: /var/www/html

bootloader_filename: ipxe-bootloader
bootloader_tftp_enabled: false
bootloader_https_enabled: true
bootloader_http_enabled: true

### release values ###
releases:
  alpinelinux:
    name: "Alpine Linux"
    mirror: "http://dl-cdn.alpinelinux.org"
    base_dir: "alpine"
    enabled: true
    menu: "linux"
    versions:
      - name: "3.10"
        code_name: "v3.10"
      - name: "Edge (development)"
        code_name: "edge"
  archlinux:
    name: "Arch Linux"
    mirror: "mirror.rackspace.com"
    base_dir: "archlinux"
    enabled: true
    menu: "linux"
    versions:
      - name: "2019.10.01"
        code_name: "2019.10.01"
  blackarch:
    name: "BlackArch"
    enabled: true
    menu: "security"
    versions:
      - name: "2019.06.01"
        code_name: "2019.06.01"
  centos:
    name: "CentOS"
    mirror: "http://mirror.centos.org"
    base_dir: "centos"
    enabled: true
    menu: "linux"
    versions:
      - name: "8.0"
        code_name: "8.0.1905"
      - name: "8.0 Stream"
        code_name: "8-stream"
      - name: "7.7"
        code_name: "7.7.1908"
  coreos:
    name: "Fedora CoreOS"
    mirror: "https://builds.coreos.fedoraproject.org"
    base_dir: "prod/streams/testing/builds"
    enabled: true
    menu: "linux"    
    versions:
      - name: "30"
        code_name: "beta"
  debian:
    name: "Debian"      
    mirror: "http://deb.debian.org"
    archive_mirror: "http://archive.debian.org"
    base_dir: "debian"
    enabled: true
    menu: "linux"    
    versions:
      stable:
        - name: "10.0 (buster)"
          code_name: "buster"
        - name: "9.0 (stretch)"
          code_name: "stretch"
        - name: "8.0 (jessie)"
          code_name: "jessie"
        - name: "7.0 (jessie)"
          code_name: "wheezy"
      testing:
        - name: "bullseye (testing)"
          code_name: "bullseye"
        - name: "sid (unstable)"
          code_name: "sid"
  devuan:
    name: "Devuan"
    mirror: "http://auto.mirror.devuan.org"
    base_dir: "devuan"
    enabled: true
    menu: "linux"
    versions:
      stable:
        - name: "ascii (stable)"
          code_name: "ascii"
        - name: "1.0 (jessie)"
          code_name: "jessie"
      testing:
        - name: "beowulf (testing)"
          code_name: "beowulf"
  fedora:
    name: "Fedora"
    mirror: "http://mirrors.kernel.org"
    base_dir: "fedora"
    enabled: true
    menu: "linux"    
    versions:
      - name: "31"
        code_name: "31"
      - name: "30"
        code_name: "30"
      - name: "29"
        code_name: "29"
  flatcar:
    name: "Container Linux by Flatcar"
    mirror: ""
    enabled: true
    menu: "linux"    
    versions:
      - name: "Stable Channel"
        code_name: "stable"
      - name: "Beta Channel"
        code_name: "beta"
      - name: "Alpha Channel"
        code_name: "alpha"
      - name: "Edge Channel"
        code_name: "edge"
  freebsd:
    name: "FreeBSD"
    enabled: false
    menu: "bsd"
    versions:
      - name: "FreeBSD 12.0"
        code_name: "12.0"
        image_subdir: "12"
      - name: "FreeBSD 11.2"
        code_name: "11.2"
        image_subdir: "11"
      - name: "FreeBSD 11.1"
        code_name: "11.1"
        image_subdir: "11"
      - name: "FreeBSD 11.0"
        code_name: "11.0"
        image_subdir: "11"
      - name: "FreeBSD 10.4"
        code_name: "10.4"
        image_subdir: "10"
  freedos:
    name: "FreeDOS"
    mirror: "http://www.freedos.org"
    base_dir: "download/download"
    enabled: true
    menu: "dos"
    versions:
      - name: "1.2 Full Installer"
        code_name: "FD12FULL"
      - name: "1.2 Lite Installer"
        code_name: "FD12LITE"
  gentoo:
    name: "Gentoo"
    mirror: ""
    enabled: false
    menu: "linux"
    versions:
      - name: "Minimal CD 20160204 (amd64)"
        code_name: "20160204"
  ipfire:
    name: "IPFire"
    mirror: "https://downloads.ipfire.org"
    menu: "linux"
    enabled: true
    versions:
      - name: "2.21 Core 126"
        code_name: "2.21-core126"
  kali:
    name: "Kali Linux"
    mirror: "http://http.kali.org"
    base_dir: "kali"
    enabled: true
    menu: "security"
    versions:
      - name: "Rolling Edition (2019.2)"
        code_name: "rolling"
  livedebian:
    name: "Debian Live"
    mirror: "http://cdimage.debian.org"
    base_dir: "cdimage/archive"
    enabled: true
    menu: "live"
    versions:
      - name: "8.11.0"
        code_name: "8.11.0"
    flavors:
      - name: "Cinnamon"
        code_name: "cinnamon-desktop"
      - name: "Gnome"
        code_name: "gnome-desktop"
      - name: "KDE"
        code_name: "kde-desktop"
      - name: "LXDE"
        code_name: "lxde-desktop"
      - name: "MATE"
        code_name: "mate-desktop"
      - name: "Standard"
        code_name: "standard"
      - name: "XFCE"
        code_name: "xfce-desktop"
  livegrml:
    name: "Grml Live Linux"
    mirror: "http://download.grml.org"
    enabled: true
    menu: "live"
    versions:
      - name: "2018.12 Full"
        code_name: "grml-full"
      - name: "2018.12 Small"
        code_name: "grml-small"
  mageia:
    name: "Mageia"
    mirror: "http://mirrors.kernel.org"
    base_dir: "mageia"
    enabled: true
    menu: "linux"
    versions:
      - name: "7.1"
        code_name: "7.1"
      - name: "cauldron"
        code_name: "cauldron"
  nixos:
    name: "NixOS"
    enabled: true
    menu: "linux"
    versions:
      - name: "Nixos 19.09"
        code_name: "19.09"
      - name: "Nixos 19.03"
        code_name: "19.03"
      - name: "Nixox Unstable"
        code_name: "unstable"
  openbsd:
    name: "OpenBSD"
    mirror: "http://ftp.openbsd.org"
    base_dir: "pub/OpenBSD"
    enabled: true
    menu: "bsd"
    versions:
      - name: "6.6"
        code_name: "6.6"
        image_ver: "66"
      - name: "6.5"
        code_name: "6.5"
        image_ver: "65"
      - name: "6.4"
        code_name: "6.4"
        image_ver: "64"
      - name: "6.3"
        code_name: "6.3"
        image_ver: "63"
      - name: "6.6 Latest Snapshot"
        code_name: "snapshots"
        image_ver: "66"
  opensuse:
    name: "OpenSUSE"
    mirror: "http://download.opensuse.org"
    base_dir: "distribution/leap"
    enabled: true
    menu: "linux"
    versions:
      - name: "openSUSE Leap 15.1"
        code_name: "15.1"
      - name: "openSUSE Leap 15.0"
        code_name: "15.0"
      - name: "openSUSE Leap 42.3"
        code_name: "42.3"
      - name: "openSUSE tumbleweed"
        code_name: "tumbleweed"
  parrotsec:
    name: "Parrot Security"
    mirror: "https://mirrordirector.archive.parrotsec.org"
    base_dir: "parrot"
    enabled: true
    menu: "security"
    versions:
      - name: "Stable Netinstall"
        code_name: "stable"
  rancheros:
    name: "RancherOS"
    mirror: "http://releases.rancher.com"
    base_dir: "os/latest"
    enabled: true
    menu: "linux"
    versions:
      - name: "Latest (20 MB)"
        code_name: "latest"
  scientific:
    name: "Scientific Linux"
    mirror: "http://ftp1.scientificlinux.org"
    base_dir: ""
    enabled: true
    menu: "linux"
    versions:
      - name: "7.7"
        code_name: "7.7"
      - name: "7.6"
        code_name: "7.6"
      - name: "6.10"
        code_name: "6.10"
      - name: "6.9"
        code_name: "6.9" 
  slackware:
    name: "Slackware"
    mirror: "http://mirror.rackspace.com"
    base_dir: "slackware"
    enabled: true
    menu: "linux"
    versions:
      - name: "Current"
        code_name: "current"
      - name: "14.2"
        code_name: "14.2"
      - name: "14.1"
        code_name: "14.1"
  tinycore:
    name: "Tiny Core Linux"
    mirror: "http://tinycorelinux.net"
    enabled: true
    menu: "linux"
    versions:
      - name: "Core [ISO]"
        code_name: "Core"
      - name: "TinyCore [ISO]"
        code_name: "TinyCore"
      - name: "CorePlus [ISO]"
        code_name: "CorePlus"
  ubuntu:
    name: "Ubuntu"
    mirror: "http://archive.ubuntu.com"
    archive_mirror: "http://old-releases.ubuntu.com"
    base_dir: "ubuntu"
    enabled: true
    menu: "linux"
    versions:
      - name: "19.10 Eoan Ermine"
        code_name: "eoan"
      - name: "19.04 Disco Dingo"
        code_name: "disco"
      - name: "18.04 LTS Bionic Beaver"
        code_name: "bionic"
      - name: "16.04 LTS Xenial Xerus"
        code_name: "xenial"

# utility values
utilities:
  avg:
    name: "AVG Rescue CD"
    enabled: true
    menu: "pcbios"
    type: "memdisk"
    version: "160420a12074"
    util_path: "http://download.avg.com/filedir/inst/avg_arl_cdi_all_120_160420a12074.iso"
  breakin:
    name: "Breakin"
    enabled: true
    menu: "pcbios"
    type: "memdisk"
    version: "4.26.1-53"
    util_path: "http://www.advancedclustering.com/wp-content/uploads/2017/02/bootimage-4.26.1-53.iso"
  clonezilla:
    name: "Clonezilla"
    enabled: true
    menu: "pcbios"
    type: "memdisk"
    version: "2.6.2-15"
    util_path: "http://master.dl.sourceforge.net/project/clonezilla/clonezilla_live_stable/2.6.2-15/clonezilla-live-2.6.2-15-amd64.iso"
  dban:
    name: "DBAN"
    enabled: true
    menu: "pcbios"
    type: "memdisk"
    version: "2.3.0"
    util_path: "http://master.dl.sourceforge.net/project/dban/dban/dban-2.3.0/dban-2.3.0_i586.iso"
  gparted:
    name: "GParted"
    enabled: true
    menu: "pcbios"
    type: "memdisk"
    version: "1.0.0-3"
    util_path: "http://master.dl.sourceforge.net/project/gparted/gparted-live-stable/1.0.0-3/gparted-live-1.0.0-3-amd64.iso"
  memtest:
    name: "Memtest"
    enabled: true
    menu: "pcbios"
    type: "memtest"
    version: "5.01.0"
    util_path: "https://boot.netboot.xyz/utils/memtest86-5.01.0"
  supergrub:
    name: "SuperGRUB"
    enabled: true
    menu: "pcbios"
    type: "memdisk"
    version: "2.04s1"
    util_path: "http://master.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso"
  ubcd:
    name: "Ultimate Boot CD (UBCD)"
    enabled: true
    menu: "pcbios"
    type: "memdisk"
    version: "538"
    util_path: "http://mirror.sysadminguide.net/ubcd/ubcd538.iso"