---

### site configuration ###
site_name: netboot.xyz
boot_domain: boot.netboot.xyz
boot_version: "2.x"
boot_timeout: 300000
time_server: "0.pool.ntp.org"

# signature checking
sigs_menu: false
sigs_enabled: false

# helper app locations
memdisk_location: "http://${boot_domain}/memdisk"
wimboot_location: "http://${boot_domain}/wimboot"

# iPXE upstream repo settings
ipxe_repo: https://github.com/ipxe/ipxe
ipxe_branch: master

ipxe_source_dir: /usr/src/ipxe
netbootxyz_root: /var/www/html
netbootxyz_conf_dir: /etc/netbootxyz

# live os settings
live_endpoint: "https://github.com/netbootxyz"

# generates menus
generate_menus: true
generate_version_file: true

# generates signatures for source files
generate_checksums: true
checksums_filename: "{{ site_name }}-sha256-checksums.txt"

# pciids
pciids_url: https://raw.githubusercontent.com/netbootxyz/pciids/master/pciids.ipxe

# bootloader options
generate_disks: true
generate_disks_legacy: true
generate_disks_efi: true
generate_disks_arm: false
bootloader_https_enabled: true
bootloader_http_enabled: true
bootloader_disks:
  - "netboot.xyz"

# custom menus
# custom_github_menus allows for github custom menus
# custom_generate_menus allows for self hosted custom menus to be added
custom_github_menus: true
custom_generate_menus: false
custom_templates_dir: "{{ netbootxyz_conf_dir }}/custom"

# signature generation
generate_signatures: false
sigs_dir: "{{ netbootxyz_root }}/sigs"
sigs_location: "http://${boot_domain}/sigs/"
cert_dir: "/etc/netbootxyz/certs"
ipxe_trust_args: "TRUST={{ ipxe_ca_location }}"
ipxe_ca_url: http://ca.ipxe.org/ca.crt
ipxe_ca_filename: ca-ipxe-org.crt
codesign_cert_filename: codesign.crt
codesign_key_filename: codesign.key
cert_file_filename : ca-netboot-xyz.crt

#bootloader_multiple: true
#bootloader_disks:
#  - "netboot.xyz"
#  - "netboot.xyz-packet"
    
### release values ###
releases:
  alpinelinux:
    name: "Alpine Linux"
    mirror: "http://dl-cdn.alpinelinux.org"
    base_dir: "alpine"
    enabled: true
    menu: "linux"
    versions:
      - name: "3.11"
        code_name: "v3.11"
      - name: "Edge (development)"
        code_name: "edge"
  archlinux:
    name: "Arch Linux"
    mirror: "mirror.rackspace.com"
    base_dir: "archlinux"
    enabled: true
    menu: "linux"
    versions:
      - name: "2020.01.01"
        code_name: "2020.01.01"
  blackarch:
    name: "BlackArch"
    enabled: true
    menu: "security"
    versions:
      - name: "2020.01.01"
        code_name: "2020.01.01"
  centos:
    name: "CentOS"
    mirror: "http://mirror.centos.org"
    base_dir: "centos"
    enabled: true
    menu: "linux"
    versions:
      - name: "8.0"
        code_name: "8.0.1905"
      - name: "8.0 Stream"
        code_name: "8-stream"
      - name: "7.7"
        code_name: "7.7.1908"
  coreos:
    name: "Fedora CoreOS"
    mirror: "https://builds.coreos.fedoraproject.org"
    base_dir: "prod/streams/testing/builds"
    enabled: false
    menu: "linux"    
    versions:
      - name: "31"
        code_name: "31.20191127.1"
  debian:
    name: "Debian"      
    mirror: "http://deb.debian.org"
    archive_mirror: "http://archive.debian.org"
    base_dir: "debian"
    enabled: true
    menu: "linux"    
    versions:
      stable:
        - name: "10.0 (buster)"
          code_name: "buster"
        - name: "9.0 (stretch)"
          code_name: "stretch"
      testing:
        - name: "bullseye (testing)"
          code_name: "bullseye"
        - name: "sid (unstable)"
          code_name: "sid"
  devuan:
    name: "Devuan"
    mirror: "http://auto.mirror.devuan.org"
    base_dir: "devuan"
    enabled: false
    menu: "linux"
    versions:
      stable:
        - name: "ascii (stable)"
          code_name: "ascii"
        - name: "1.0 (jessie)"
          code_name: "jessie"
      testing:
        - name: "beowulf (testing)"
          code_name: "beowulf"
  fedora:
    name: "Fedora"
    mirror: "http://mirrors.kernel.org"
    base_dir: "fedora"
    enabled: true
    menu: "linux"    
    versions:
      - name: "31"
        code_name: "31"
      - name: "30"
        code_name: "30"
      - name: "29"
        code_name: "29"
  flatcar:
    name: "Container Linux by Flatcar"
    mirror: ""
    enabled: true
    menu: "linux"    
    versions:
      - name: "Stable Channel"
        code_name: "stable"
      - name: "Beta Channel"
        code_name: "beta"
      - name: "Alpha Channel"
        code_name: "alpha"
  freebsd:
    name: "FreeBSD"
    enabled: true
    menu: "bsd"
  freedos:
    name: "FreeDOS"
    mirror: "http://www.freedos.org"
    base_dir: "download/download"
    enabled: true
    menu: "dos"
    versions:
      - name: "1.2 Full Installer"
        code_name: "FD12FULL"
      - name: "1.2 Lite Installer"
        code_name: "FD12LITE"
  gentoo:
    name: "Gentoo"
    mirror: ""
    enabled: false
    menu: "linux"
    versions:
      - name: "Minimal CD 20160204 (amd64)"
        code_name: "20160204"
  ipfire:
    name: "IPFire"
    mirror: "https://downloads.ipfire.org"
    base_dir: "releases/ipfire-2.x"
    menu: "linux"
    enabled: true
    versions:
      - name: "2.23 Core 138"
        code_name: "2.23-core138"
  k3os:
    name: "k3OS"
    mirror: "https://github.com/rancher/k3os/releases/download/"
    enabled: true
    menu: "linux"
    versions:
      - name: "v0.8.0"
        code_name: "v0.8.0"
  kali:
    name: "Kali Linux"
    mirror: "http://http.kali.org"
    base_dir: "kali"
    enabled: true
    menu: "linux"
    versions:
      - name: "Rolling Edition (2019.4)"
        code_name: "rolling"
  livegrml:
    name: "Grml Live Linux"
    mirror: "http://download.grml.org"
    enabled: true
    menu: "live"
    versions:
      - name: "2018.12 Full"
        code_name: "grml-full"
      - name: "2018.12 Small"
        code_name: "grml-small"
  mageia:
    name: "Mageia"
    mirror: "http://mirrors.kernel.org"
    base_dir: "mageia"
    enabled: true
    menu: "linux"
    versions:
      - name: "7.1"
        code_name: "7.1"
      - name: "cauldron"
        code_name: "cauldron"
  nixos:
    name: "NixOS"
    enabled: true
    menu: "linux"
    versions:
      - name: "Nixos 19.09"
        code_name: "19.09"
      - name: "Nixos 19.03"
        code_name: "19.03"
  openbsd:
    name: "OpenBSD"
    mirror: "http://ftp.openbsd.org"
    base_dir: "pub/OpenBSD"
    enabled: true
    menu: "bsd"
    versions:
      - name: "6.6"
        code_name: "6.6"
        image_ver: "66"
      - name: "6.5"
        code_name: "6.5"
        image_ver: "65"
      - name: "6.4"
        code_name: "6.4"
        image_ver: "64"
      - name: "6.3"
        code_name: "6.3"
        image_ver: "63"
      - name: "6.6 Latest Snapshot"
        code_name: "snapshots"
        image_ver: "66"
  opensuse:
    name: "OpenSUSE"
    mirror: "http://download.opensuse.org"
    base_dir: "distribution/leap"
    enabled: true
    menu: "linux"
    versions:
      - name: "openSUSE Leap 15.1"
        code_name: "15.1"
      - name: "openSUSE Leap 15.0"
        code_name: "15.0"
      - name: "openSUSE Leap 42.3"
        code_name: "42.3"
      - name: "openSUSE tumbleweed"
        code_name: "tumbleweed"
  oracle:
    name: "Oracle Linux"
    mirror: "https://yum.oracle.com"
    enabled: true
    menu: "linux"
    paths:
      7: "/repo/OracleLinux/OL7/latest/x86_64"
      8: "/repo/OracleLinux/OL8/baseos/latest/x86_64" 
  parrotsec:
    name: "Parrot Security"
    mirror: "https://mirrordirector.archive.parrotsec.org"
    base_dir: "parrot"
    enabled: true
    menu: "security"
    versions:
      - name: "Stable Netinstall"
        code_name: "stable"
  rancheros:
    name: "RancherOS"
    mirror: "http://releases.rancher.com"
    base_dir: "os/latest"
    enabled: true
    menu: "linux"
    versions:
      - name: "Latest (20 MB)"
        code_name: "latest"
  rhel:
    name: "Red Hat Enterprise Linux"
    enabled: true
    menu: "linux"
  scientific:
    name: "Scientific Linux"
    mirror: "http://ftp1.scientificlinux.org"
    base_dir: "linux/scientific"
    enabled: true
    menu: "linux"
    versions:
      - name: "7.7"
        code_name: "7.7"
      - name: "7.6"
        code_name: "7.6"
      - name: "6.10"
        code_name: "6.10"
      - name: "6.9"
        code_name: "6.9" 
  slackware:
    name: "Slackware"
    mirror: "http://mirror.rackspace.com"
    base_dir: "slackware"
    enabled: true
    menu: "linux"
    versions:
      - name: "Current"
        code_name: "current"
      - name: "14.2"
        code_name: "14.2"
      - name: "14.1"
        code_name: "14.1"
  tinycore:
    name: "Tiny Core Linux"
    mirror: "http://tinycorelinux.net"
    enabled: true
    menu: "linux"
    versions:
      - name: "Core [ISO]"
        code_name: "Core"
      - name: "TinyCore [ISO]"
        code_name: "TinyCore"
  ubuntu:
    name: "Ubuntu"
    mirror: "http://archive.ubuntu.com"
    archive_mirror: "http://old-releases.ubuntu.com"
    base_dir: "ubuntu"
    enabled: true
    menu: "linux"
    versions:
      - name: "19.10 Eoan Ermine"
        code_name: "eoan"
      - name: "19.04 Disco Dingo"
        code_name: "disco"
      - name: "18.04 LTS Bionic Beaver"
        code_name: "bionic"
      - name: "16.04 LTS Xenial Xerus"
        code_name: "xenial"

# utility values
utilitiespcbios:
  avg:
    name: "AVG Rescue CD"
    enabled: true
    type: "memdisk"
    version: "160420a12074"
    util_path: "http://download.avg.com/filedir/inst/avg_arl_cdi_all_120_160420a12074.iso"
  breakin:
    name: "Breakin"
    enabled: true
    type: "direct"
    kernel: "${live_endpoint}{{ endpoints.breakin.path }}vmlinuz sshpasswd=breakin startup=breakin initrd=initrd"
    initrd: "${live_endpoint}{{ endpoints.breakin.path }}initrd"
  clonezilla:
    name: "Clonezilla"
    enabled: true
    type: "ipxemenu"
  dban:
    name: "DBAN"
    enabled: true
    type: "ipxemenu"
  gparted:
    name: "GParted"
    enabled: true
    type: "memdisk"
    version: "1.0.0-3"
    util_path: "http://master.dl.sourceforge.net/project/gparted/gparted-live-stable/1.0.0-3/gparted-live-1.0.0-3-amd64.iso"
  grml:
    name: "Grml"
    enabled: true
    type: "ipxemenu"
  memtest:
    name: "Memtest"
    enabled: true
    type: "memtest"
    version: "5.01.0"
    util_path: "https://boot.netboot.xyz/utils/memtest86-5.01.0"
  supergrub:
    name: "SuperGRUB"
    enabled: true
    type: "memdisk"
    version: "2.04s1"
    util_path: "http://master.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso"
  ubcd:
    name: "Ultimate Boot CD (UBCD)"
    enabled: true
    type: "memdisk"
    version: "538"
    util_path: "http://mirror.sysadminguide.net/ubcd/ubcd538.iso"

# efi utility values
utilitiesefi:
  clonezilla:
    name: "Clonezilla"
    enabled: true
    type: "ipxemenu"
  grml:
    name: "Grml"
    enabled: true
    type: "ipxemenu"

bootloaders:
  legacy:
    - type: "ISO"
      ipxe_bin: "ipxe.iso"
      output_bin: ".iso"
      desc: "Used for CD/DVD, Virtual CDs, DRAC/iLO, VMware, Virtual Box"
    - type: "USB"
      ipxe_bin: "ipxe.usb"
      output_bin: ".usb"
      desc: "Used for creation of USB Keys"
    - type: "Kernel"
      ipxe_bin: "ipxe.lkrn"
      output_bin: ".lkrn"
      desc: "Used for booting from GRUB/EXTLINUX"
    - type: "Floppy"
      ipxe_bin: "ipxe.dsk"
      output_bin: ".dsk"
      desc: "Virtual floppy disk for DRAC/iLO, VMware, Virtual Box, etc"
    - type: "DHCP"
      ipxe_bin: "ipxe.kpxe"
      output_bin: ".kpxe"
      desc: "DHCP boot image file, uses built-in iPXE NIC drivers"
    - type: "DHCP-undionly"
      ipxe_bin: "undionly.kpxe"
      output_bin: "-undionly.kpxe"
      desc: "DHCP boot image file, use if you have NIC issues"
  uefi:
    - type: "ISO"
      ipxe_bin: "ipxe-efi.eiso"
      output_bin: "-efi.iso"
      desc: "EFI BIOS, works in Virtual Box EFI mode"
    - type: "USB"
      ipxe_bin: "ipxe-efi.usb"
      output_bin: "-efi.usb"
      desc: "Used for creation of USB Keys"
    - type: "DHCP"
      ipxe_bin: "ipxe.efi"
      output_bin: ".efi"
      desc: "DHCP EFI boot image file, uses built-in iPXE NIC drivers"
    - type: "DHCP-snp"
      ipxe_bin: "snp.efi"
      output_bin: "-snp.efi"
      desc: "EFI w/ Simple Network Protocol, attempts to boot all net devices"
    - type: "DHCP-snponly"
      ipxe_bin: "snponly.efi"
      output_bin: "-snponly.efi"
      desc: "EFI w/ Simple Network Protocol, only boots from device chained from"
