boot_domain: boot.netboot.xyz
boot_timeout: 300000
boot_version: 2.x
bootloader_disks:
- netboot.xyz
bootloader_http_enabled: true
bootloader_https_enabled: true
bootloaders:
  legacy:
  - desc: Used for CD/DVD, Virtual CDs, DRAC/iLO, VMware, Virtual Box
    ipxe_bin: ipxe.iso
    output_bin: .iso
    type: ISO
  - desc: Used for creation of USB Keys
    ipxe_bin: ipxe.usb
    output_bin: .usb
    type: USB
  - desc: Used for booting from GRUB/EXTLINUX
    ipxe_bin: ipxe.lkrn
    output_bin: .lkrn
    type: Kernel
  - desc: Virtual floppy disk for DRAC/iLO, VMware, Virtual Box, etc
    ipxe_bin: ipxe.dsk
    output_bin: .dsk
    type: Floppy
  - desc: DHCP boot image file, uses built-in iPXE NIC drivers
    ipxe_bin: ipxe.kpxe
    output_bin: .kpxe
    type: DHCP
  - desc: DHCP boot image file, use if you have NIC issues
    ipxe_bin: undionly.kpxe
    output_bin: -undionly.kpxe
    type: DHCP-undionly
  uefi:
  - desc: EFI BIOS, works in Virtual Box EFI mode
    ipxe_bin: ipxe-efi.eiso
    output_bin: -efi.iso
    type: ISO
  - desc: Used for creation of USB Keys
    ipxe_bin: ipxe-efi.usb
    output_bin: -efi.usb
    type: USB
  - desc: DHCP EFI boot image file, uses built-in iPXE NIC drivers
    ipxe_bin: ipxe.efi
    output_bin: .efi
    type: DHCP
  - desc: EFI w/ Simple Network Protocol, attempts to boot all net devices
    ipxe_bin: snp.efi
    output_bin: -snp.efi
    type: DHCP-snp
  - desc: EFI w/ Simple Network Protocol, only boots from device chained from
    ipxe_bin: snponly.efi
    output_bin: -snponly.efi
    type: DHCP-snponly
cert_dir: /etc/netbootxyz/certs
cert_file_filename: ca-netboot-xyz.crt
checksums_filename: '{{ site_name }}-sha256-checksums.txt'
codesign_cert_filename: codesign.crt
codesign_key_filename: codesign.key
custom_generate_menus: false
custom_github_menus: true
custom_templates_dir: '{{ netbootxyz_conf_dir }}/custom'
generate_checksums: true
generate_disks: true
generate_disks_arm: false
generate_disks_efi: true
generate_disks_legacy: true
generate_menus: true
generate_signatures: false
generate_version_file: true
ipxe_branch: master
ipxe_ca_filename: ca-ipxe-org.crt
ipxe_ca_url: http://ca.ipxe.org/ca.crt
ipxe_repo: https://github.com/ipxe/ipxe
ipxe_source_dir: /usr/src/ipxe
live_endpoint: https://github.com/netbootxyz
memdisk_location: http://${boot_domain}/memdisk
netbootxyz_conf_dir: /etc/netbootxyz
netbootxyz_root: /var/www/html
pciids_url: https://raw.githubusercontent.com/netbootxyz/pciids/master/pciids.ipxe
releases:
  alpinelinux:
    base_dir: alpine
    enabled: true
    menu: linux
    mirror: http://dl-cdn.alpinelinux.org
    name: Alpine Linux
    versions:
    - code_name: v3.12
      name: '3.12'
    - code_name: edge
      name: Edge (development)
  anarchy:
    enabled: true
    menu: linux
    name: Anarchy Linux
    versions:
    - code_name: current
      name: current
  archlinux:
    base_dir: archlinux
    enabled: true
    menu: linux
    mirror: mirror.rackspace.com
    name: Arch Linux
    versions:
    - code_name: 2020.07.01
      name: 2020.07.01
  blackarch:
    enabled: true
    menu: linux
    name: BlackArch
    versions:
    - code_name: current
      name: current
  centos:
    base_dir: centos
    enabled: true
    menu: linux
    mirror: http://mirror.centos.org
    name: CentOS
    versions:
    - code_name: 8.2.2004
      name: '8.2'
    - code_name: 8.1.1911
      name: '8.1'
    - code_name: 8.0.1905
      name: '8.0'
    - code_name: 8-stream
      name: 8.0 Stream
    - code_name: 7
      name: 7.x Latest
  coreos:
    base_dir: prod/streams
    enabled: true
    menu: linux
    mirror: https://builds.coreos.fedoraproject.org
    name: Fedora CoreOS
    versions:
    - code_name: 32.20200629.3.0
      name: stable
    - code_name: 32.20200629.2.0
      name: testing
    - code_name: 32.20200625.1.0
      name: next
  debian:
    archive_mirror: http://archive.debian.org
    base_dir: debian
    enabled: true
    menu: linux
    mirror: http://deb.debian.org
    name: Debian
    versions:
      stable:
      - code_name: buster
        name: 10.0 (buster)
      - code_name: stretch
        name: 9.0 (stretch)
      testing:
      - code_name: bullseye
        name: bullseye (testing)
      - code_name: sid
        name: sid (unstable)
  devuan:
    base_dir: devuan
    enabled: true
    menu: linux
    mirror: http://deb.devuan.org
    name: Devuan
    versions:
      stable:
      - code_name: beowulf
        name: 3.0.0 Beowulf (stable)
      - code_name: ascii
        name: 2.1 ASCII (oldstable)
      - code_name: jessie
        name: 1.0 Jessie (oldoldstable)
      testing:
      - code_name: chimaera
        name: Chimaera (testing)
  fedora:
    base_dir: fedora
    enabled: true
    menu: linux
    mirror: http://mirrors.kernel.org
    name: Fedora
    versions:
    - code_name: '32'
      name: '32'
    - code_name: '31'
      name: '31'
    - code_name: '30'
      name: '30'
  flatcar:
    enabled: true
    menu: linux
    mirror: ''
    name: Container Linux by Flatcar
    versions:
    - code_name: stable
      name: Stable Channel
    - code_name: beta
      name: Beta Channel
    - code_name: alpha
      name: Alpha Channel
  freebsd:
    enabled: true
    menu: bsd
    name: FreeBSD
  freedos:
    base_dir: download/download
    enabled: true
    menu: dos
    mirror: http://www.freedos.org
    name: FreeDOS
    versions:
    - code_name: FD12FULL
      name: 1.2 Full Installer
    - code_name: FD12LITE
      name: 1.2 Lite Installer
  gentoo:
    enabled: true
    menu: linux
    name: Gentoo
  ipfire:
    base_dir: releases/ipfire-2.x
    enabled: true
    menu: linux
    mirror: https://downloads.ipfire.org
    name: IPFire
    versions:
    - code_name: 2.25-core146
      name: 2.25 Core146
  k3os:
    enabled: true
    menu: linux
    mirror: https://github.com/rancher/k3os/releases
    name: k3OS
  kali:
    base_dir: kali
    enabled: true
    menu: linux
    mirror: http://http.kali.org
    name: Kali Linux
    versions:
    - code_name: rolling
      name: Rolling Edition (2020.1)
  livegrml:
    enabled: true
    menu: live
    mirror: http://download.grml.org
    name: Grml Live Linux
    versions:
    - code_name: grml-full
      name: 2018.12 Full
    - code_name: grml-small
      name: 2018.12 Small
  mageia:
    base_dir: mageia
    enabled: true
    menu: linux
    mirror: http://mirrors.kernel.org
    name: Mageia
    versions:
    - code_name: '7.1'
      name: '7.1'
    - code_name: cauldron
      name: cauldron
  nixos:
    enabled: true
    menu: linux
    name: NixOS
  openbsd:
    base_dir: pub/OpenBSD
    enabled: true
    menu: bsd
    mirror: http://ftp.openbsd.org
    name: OpenBSD
    versions:
    - code_name: '6.6'
      image_ver: '66'
      name: '6.6'
    - code_name: '6.5'
      image_ver: '65'
      name: '6.5'
    - code_name: '6.4'
      image_ver: '64'
      name: '6.4'
    - code_name: '6.3'
      image_ver: '63'
      name: '6.3'
    - code_name: snapshots
      image_ver: '66'
      name: 6.6 Latest Snapshot
  opensuse:
    base_dir: distribution/leap
    enabled: true
    menu: linux
    mirror: http://download.opensuse.org
    name: OpenSUSE
    versions:
    - code_name: '15.2'
      name: openSUSE Leap 15.2
    - code_name: '15.1'
      name: openSUSE Leap 15.1
    - code_name: '15.0'
      name: openSUSE Leap 15.0
    - code_name: '42.3'
      name: openSUSE Leap 42.3
    - code_name: tumbleweed
      name: openSUSE tumbleweed
  oracle:
    enabled: true
    menu: linux
    mirror: https://yum.oracle.com
    name: Oracle Linux
    paths:
      7: /repo/OracleLinux/OL7/latest/x86_64
      8: /repo/OracleLinux/OL8/baseos/latest/x86_64
  parrotsec:
    enabled: true
    menu: linux
    name: Parrot Security
    versions:
    - code_name: stable
      name: Stable Netinstall
  rancheros:
    base_dir: os/latest
    enabled: true
    menu: linux
    mirror: http://releases.rancher.com
    name: RancherOS
    versions:
    - code_name: latest
      name: Latest (20 MB)
  rhel:
    enabled: true
    menu: linux
    name: Red Hat Enterprise Linux
  scientific:
    base_dir: linux/scientific
    enabled: true
    menu: linux
    mirror: http://ftp1.scientificlinux.org
    name: Scientific Linux
    versions:
    - code_name: '7.7'
      name: '7.7'
    - code_name: '7.6'
      name: '7.6'
    - code_name: '6.10'
      name: '6.10'
    - code_name: '6.9'
      name: '6.9'
  slackware:
    base_dir: slackware
    enabled: true
    menu: linux
    mirror: http://mirror.rackspace.com
    name: Slackware
    versions:
    - code_name: current
      name: Current
    - code_name: '14.2'
      name: '14.2'
    - code_name: '14.1'
      name: '14.1'
  smartos:
    base_dir: /platform/i86pc/
    enabled: true
    menu: unix
    mirror: https://netboot.joyent.com/os/
    name: SmartOS
    versions:
    - code_name: 20200716T142843Z
      name: 20200716T142843Z
    - code_name: 20200715T195011Z
      name: 20200715T195011Z
    - code_name: 20200701T231659Z
      name: 20200701T231659Z
    - code_name: 20200617T233107Z
      name: 20200617T233107Z
    - code_name: 20200603T203505Z
      name: 20200603T203505Z
    - code_name: 20200520T174734Z
      name: 20200520T174734Z
  talos:
    enabled: true
    menu: linux
    mirror: https://github.com/talos-systems/talos/releases
    name: Talos
    platforms:
    - key: metal
      name: Bare Metal
    - key: aws
      name: AWS
    - key: azure
      name: Azure
    - key: digital-ocean
      name: Digital Ocean
    - key: gcp
      name: GCP
    - key: packet
      name: Packet
    - key: vmware
      name: VMware
  tinycore:
    enabled: true
    menu: linux
    mirror: http://distro.ibiblio.org/tinycorelinux
    name: Tiny Core Linux
    versions:
    - arch: x86
      code_name: core
      initrd: /11.x/x86/release/distribution_files/core.gz
      kernel: /11.x/x86/release/distribution_files/vmlinuz
      name: Core
    - arch: x86_64
      code_name: corepure
      initrd: /11.x/x86_64/release/distribution_files/corepure64.gz
      kernel: /11.x/x86_64/release/distribution_files/vmlinuz64
      name: CorePure
    - arch: x86
      code_name: dcorebionic
      initrd: /dCore/x86/release/dCore-bionic/dCore-bionic.gz
      kernel: /dCore/x86/release/dCore-bionic/vmlinuz-bionic
      name: dCore Bionic
    - arch: x86
      code_name: dcorebionicplus
      initrd: /dCore/x86/release/dCore-bionic/dCorePlus-bionic.gz
      kernel: /dCore/x86/release/dCore-bionic/vmlinuz-bionic
      name: dCore Bionic Plus
    - arch: x86
      code_name: dcorejessie
      initrd: /dCore/x86/release/dCore-jessie/dCore-jessie.gz
      kernel: /dCore/x86/release/dCore-jessie/vmlinuz-jessie
      name: dCore Jessie
    - arch: x86
      code_name: dcorejessieplus
      initrd: /dCore/x86/release/dCore-jessie/dCorePlus-jessie.gz
      kernel: /dCore/x86/release/dCore-jessie/vmlinuz-jessie
      name: dCore Jessie Plus
    - arch: x86
      code_name: dcorestretch
      initrd: /dCore/x86/release/dCore-stretch/dCore-stretch.gz
      kernel: /dCore/x86/release/dCore-stretch/vmlinuz-stretch
      name: dCore Stretch
    - arch: x86
      code_name: dcorestretchplus
      initrd: /dCore/x86/release/dCore-stretch/dCorePlus-stretch.gz
      kernel: /dCore/x86/release/dCore-stretch/vmlinuz-stretch
      name: dCore Stretch Plus
    - arch: x86
      code_name: dcoretrusty
      initrd: /dCore/x86/release/dCore-trusty/dCore-trusty.gz
      kernel: /dCore/x86/release/dCore-trusty/vmlinuz-trusty
      name: dCore Trusty
    - arch: x86
      code_name: dcoretrustyplus
      initrd: /dCore/x86/release/dCore-trusty/dCorePlus-trusty.gz
      kernel: /dCore/x86/release/dCore-trusty/vmlinuz-trusty
      name: dCore Trusty Plus
    - arch: x86
      code_name: dcorewheezy
      initrd: /dCore/x86/release/dCore-wheezy/dCore-wheezy.gz
      kernel: /dCore/x86/release/dCore-wheezy/vmlinuz-wheezy
      name: dCore Wheezy
    - arch: x86
      code_name: dcorewheezyplus
      initrd: /dCore/x86/release/dCore-wheezy/dCorePlus-wheezy.gz
      kernel: /dCore/x86/release/dCore-wheezy/vmlinuz-wheezy
      name: dCore Wheezy Plus
    - arch: x86
      code_name: dcorexenial
      initrd: /dCore/x86/release/dCore-xenial/dCore-xenial.gz
      kernel: /dCore/x86/release/dCore-xenial/vmlinuz-xenial
      name: dCore Xenial
    - arch: x86
      code_name: dcorexenialplus
      initrd: /dCore/x86/release/dCore-xenial/dCorePlus-xenial.gz
      kernel: /dCore/x86/release/dCore-xenial/vmlinuz-xenial
      name: dCore Xenial Plus
    - arch: x86_64
      code_name: dcore64bionic
      initrd: /dCore/x86_64/release/dCore-bionic64/dCore-bionic64.gz
      kernel: /dCore/x86_64/release/dCore-bionic64/vmlinuz-bionic64
      name: dCore64 Bionic
    - arch: x86_64
      code_name: dcore64bionicplus
      initrd: /dCore/x86_64/release/dCore-bionic64/dCorePlus-bionic64.gz
      kernel: /dCore/x86_64/release/dCore-bionic64/vmlinuz-bionic64
      name: dCore64 Bionic Plus
    - arch: x86_64
      code_name: dcore64buster
      initrd: /dCore/x86_64/release/dCore-buster64/dCore-buster64.gz
      kernel: /dCore/x86_64/release/dCore-buster64/vmlinuz-buster64
      name: dCore64 Buster
    - arch: x86_64
      code_name: dcore64busterplus
      initrd: /dCore/x86_64/release/dCore-buster64/dCorePlus-buster64.gz
      kernel: /dCore/x86_64/release/dCore-buster64/vmlinuz-buster64
      name: dCore64 Buster Plus
    - arch: x86_64
      code_name: dcore64stretch
      initrd: /dCore/x86_64/release/dCore-stretch64/dCore-stretch64.gz
      kernel: /dCore/x86_64/release/dCore-stretch64/vmlinuz-stretch64
      name: dCore64 Stretch
    - arch: x86_64
      code_name: dcore64stretchplus
      initrd: /dCore/x86_64/release/dCore-stretch64/dCorePlus-stretch64.gz
      kernel: /dCore/x86_64/release/dCore-stretch64/vmlinuz-stretch64
      name: dCore Stretch Plus
  ubuntu:
    archive_mirror: http://old-releases.ubuntu.com
    base_dir: ubuntu
    enabled: true
    menu: linux
    mirror: http://archive.ubuntu.com
    name: Ubuntu
    versions:
    - code_name: focal
      name: 20.04 LTS Focal Fossa
    - code_name: eoan
      name: 19.10 Eoan Ermine
    - code_name: bionic
      name: 18.04 LTS Bionic Beaver
    - code_name: xenial
      name: 16.04 LTS Xenial Xerus
  zeninstall:
    enabled: true
    menu: linux
    name: Zen Installer Arch
    versions:
    - code_name: current
      name: current
sigs_dir: '{{ netbootxyz_root }}/sigs'
sigs_enabled: false
sigs_location: http://${boot_domain}/sigs/
sigs_menu: false
site_name: netboot.xyz
time_server: 0.pool.ntp.org
utilitiesarm:
  placeholder:
    enabled: false
    name: placeholder
    type: direct
utilitiesefi:
  4mlinux:
    enabled: true
    name: 4MLinux
    type: ipxemenu
  bootrepair:
    enabled: true
    initrd: ${live_endpoint}{{ endpoints.bootrepair.path }}initrd
    kernel: ${live_endpoint}{{ endpoints.bootrepair.path }}vmlinuz ip=dhcp boot=casper
      netboot=http fetch=${live_endpoint}{{ endpoints.bootrepair.path }}filesystem.squashfs
      initrd=initrd
    name: Boot Repair CD
    type: direct
  caine:
    enabled: true
    initrd: ${live_endpoint}{{ endpoints.caine.path }}initrd
    kernel: ${live_endpoint}{{ endpoints.caine.path }}vmlinuz ip=dhcp boot=casper
      netboot=http fetch=${live_endpoint}{{ endpoints.caine.path }}filesystem.squashfs
      initrd=initrd
    name: CAINE
    type: direct
  clonezilla:
    enabled: true
    name: Clonezilla
    type: ipxemenu
  gparted:
    enabled: true
    name: GParted
    type: ipxemenu
  grml:
    enabled: true
    name: Grml
    type: ipxemenu
  kaspersky:
    enabled: true
    name: Kaspersky Rescue Disk
    type: ipxemenu
  rescatux:
    enabled: true
    initrd: ${live_endpoint}{{ endpoints.rescatux.path }}initrd
    kernel: ${live_endpoint}{{ endpoints.rescatux.path }}vmlinuz boot=live fetch=${live_endpoint}{{
      endpoints.rescatux.path }}filesystem.squashfs selinux=1 security=selinux enforcing=0
      initrd=initrd
    name: Rescatux
    type: direct
  systemrescue:
    enabled: true
    name: System Rescue CD
    type: ipxemenu
utilitiespcbios:
  4mlinux:
    enabled: true
    name: 4MLinux
    type: ipxemenu
  avg:
    enabled: true
    name: AVG Rescue CD
    type: memdisk
    util_path: http://download.avg.com/filedir/inst/avg_arl_cdi_all_120_160420a12074.iso
    version: 160420a12074
  bootrepair:
    enabled: true
    initrd: ${live_endpoint}{{ endpoints.bootrepair.path }}initrd
    kernel: ${live_endpoint}{{ endpoints.bootrepair.path }}vmlinuz ip=dhcp boot=casper
      netboot=http fetch=${live_endpoint}{{ endpoints.bootrepair.path }}filesystem.squashfs
      initrd=initrd
    name: Boot Repair CD
    type: direct
  breakin:
    enabled: true
    initrd: ${live_endpoint}{{ endpoints.breakin.path }}initrd
    kernel: ${live_endpoint}{{ endpoints.breakin.path }}vmlinuz sshpasswd=breakin
      startup=breakin initrd=initrd
    name: Breakin
    type: direct
  caine:
    enabled: true
    initrd: ${live_endpoint}{{ endpoints.caine.path }}initrd
    kernel: ${live_endpoint}{{ endpoints.caine.path }}vmlinuz ip=dhcp boot=casper
      netboot=http fetch=${live_endpoint}{{ endpoints.caine.path }}filesystem.squashfs
      initrd=initrd
    name: CAINE
    type: direct
  clonezilla:
    enabled: true
    name: Clonezilla
    type: ipxemenu
  dban:
    enabled: true
    name: DBAN
    type: ipxemenu
  gparted:
    enabled: true
    name: GParted
    type: ipxemenu
  grml:
    enabled: true
    name: Grml
    type: ipxemenu
  kaspersky:
    enabled: true
    name: Kaspersky Rescue Disk
    type: ipxemenu
  memtest:
    enabled: true
    name: Memtest
    type: memtest
    util_path: https://boot.netboot.xyz/utils/memtest86-5.01.0
    version: 5.01.0
  rescatux:
    enabled: true
    initrd: ${live_endpoint}{{ endpoints.rescatux.path }}initrd
    kernel: ${live_endpoint}{{ endpoints.rescatux.path }}vmlinuz boot=live fetch=${live_endpoint}{{
      endpoints.rescatux.path }}filesystem.squashfs selinux=1 security=selinux enforcing=0
      initrd=initrd
    name: Rescatux
    type: direct
  supergrub:
    enabled: true
    name: SuperGRUB
    type: memdisk
    util_path: http://master.dl.sourceforge.net/project/supergrub2/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso
    version: 2.04s1
  systemrescue:
    enabled: true
    name: System Rescue CD
    type: ipxemenu
  ubcd:
    enabled: true
    name: Ultimate Boot CD (UBCD)
    type: memdisk
    util_path: http://mirror.sysadminguide.net/ubcd/ubcd538.iso
    version: '538'
wimboot_location: http://${boot_domain}/wimboot
